### ISSUE TITLE
Add amphotericin as a resource type

### ISSUE THREAD

**Issue by rgxai** [covidarmy/backend#119]
We need to add amphotericin (which is a drug for black fungus) to our resource types

- Add the above to tweet fetch query "amphotericin"
- Add it to the resources.json
- add it to categories file under the medicine category

**Comment by SwarnimWalavalkar** [comment]
Closed by https://github.com/covidarmy/backend/commit/885ba25e0ad7d4a8bf8a953ddf992d74aae5df1e
