### ISSUE TITLE
Changes in emptyCities endpoint

### ISSUE THREAD

**Issue by rgxai** [covidarmy/backend#136]
Currently the emptyCities endpoint returns list of cities which have total contact count of less than 10. We need to change this to return all cities in the State and remove the <10 check.

The reason we need to do this is in order to show the list of other cities and combos in a particular state on the volunteer dashboard.

**Comment by SwarnimWalavalkar** [comment]
Closed by https://github.com/covidarmy/backend/commit/3a0ad13a2796bd9344d43c92592bff4e360841c9
