### ISSUE TITLE
+1 the total requests for a particular city if checkCity API is hit

### ISSUE THREAD

**Issue by rgxai** [covidarmy/backend#137]
Currently, we only +1 the total request count for a city when a call to contacts endpoint is made. However, on our Whatsapp chatbot, we don't proceed forward with the contact endpoint unless a city has at least a few contacts.

The problem here is, the cities that have 0 data, will never show up on the chatbot and their contacts endpoint will never get hit thus they will never have a +1 on their count.

To track this, we need to +1 on that city's total resource count when the checkCity API is hit.

**Comment by SwarnimWalavalkar** [comment]
Closed by https://github.com/covidarmy/backend/commit/3a0ad13a2796bd9344d43c92592bff4e360841c9
