### ISSUE TITLE
Bug: Tweet Duplicates

### ISSUE THREAD

**Issue by Utkarshbhimte** [covidarmy/backend#19]
![image](https://user-images.githubusercontent.com/13379773/116594866-4f65ba00-a940-11eb-8ea8-3081b1094913.png)
src: https://covid.army/chennai/remdesivir

There are still duplicates in our database. can we add a unique index on tweetID on MongoDB itself?
reference: https://docs.mongodb.com/manual/core/index-unique/

**Comment by rgxai** [comment]
There is already a unique index on tweetID on mongoDB. this might be an old issue I don't think there are any more duplicates now.

**Comment by Utkarshbhimte** [comment]
Any plans for database cleanup?

**Comment by rgxai** [comment]
Yes. @anshulagx will work on it day after tomorrow.

**Comment by Utkarshbhimte** [comment]
awesome 😊

Regards
Utkarsh Bhimte
