### ISSUE TITLE
Ranking System

### ISSUE THREAD

**Issue by SwarnimWalavalkar** [covidarmy/backend#63]
## Proposed Logic
Pipeline:
Feedback -> ranking -> load balancing

Feedback system:
A queue of the latest 10 votes

API endpoint to add a vote

Ranking system:
The ranking system runs every 10 votes

Take into account the latest 10 votes for every lead, assign a score based on that.

5 (or higher) of the most recent votes *helpful*: put lead in short cooldown to avoid overload

3 of the most recent votes *unresponsive*: short cooldown
>3 of the most recent votes *unresponsive*: medium cooldown

>=5 of the most recent votes *no stock*: long cooldown

>=5 of the most recent votes *invalid*: blacklist

Load Balancing System:
Will be called by the API Logic, will return leads based on their score

**Comment by rgxai** [comment]
Compute average of last N votes upto maximum of 3
Score across different values {-2 invalid, -1 unresponsive, 0 busy, 1 nostock, 2 helpful}
Volunteer added and verified = yes gives a default score of 3
Volunteer added but not verified = 1
Remove contacts that have a value less than -1 but minimum of 2 votes in the array
If there is only one vote in the array, then don’t delete it
Recompute only for the top 10 updatedAt fields
Highest of the scored in the most recent order
Default score of all newly added contacts is 0 for twitter contacts (edited) 
take care of dependencies
