### ISSUE TITLE
Store only one number, resource type and city for each tweet

### ISSUE THREAD

**Issue by rgxai** [covidarmy/backend#67]
Currently we are storing multiple numbers per tweet but not parsing it for multiple resource types and city types due to the complexity of mapping phone, city and resource if a tweet contains multiple phone numbers, resources and cities

It is essential for us to store only one number in a mongo document so that we can take feedback against it from the chatbot. If the phone field is an array, it will become difficult to get feedback on each number separately within that array

An alternative solution is to split up tweets which contain multiple numbers into two different objects but that will lead to duplicate tweets being stored in our DB

Hence we have decided to store only one number, resource and city from 1 single tweet to simplify our approach. We also assume that if a number is working and is verified, it will pop up somewhere again on the twitter search API or some volunteer might add that number to our DB

**Comment by ms337** [comment]
We moved to using a Contact resource instead.
