### ISSUE TITLE
Implement POST Endpoint to add new contacts to DB

### ISSUE THREAD

**Issue by SwarnimWalavalkar** [covidarmy/backend#82]
### Headers:
**required:**
Authorization: <<AUTH_TOKEN>>

### Request JSON Body:
**required:**
`city`, `phone_no`, and `resource_type`

### Responses:
201 OR 400 OR 401 OR 500

**Comment by ms337** [comment]
POST /api/contacts/{location}/{resource}/ 

Request:
JSON Body contains at minimum the required contact fields

Response:
200 or ERROR

**Comment by rgxai** [comment]
Add auth to this API endpoint
